name: unit-test-verification

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.27.1
      - name: Create placeholder ..env.firebase
        run: echo "FIREBASE_CONFIG_PLACEHOLDER=true" > ..env.firebase

      - run: flutter pub get
      - run: flutter test --coverage

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}